import { createContext, useContext, useState, ReactNode } from "react";

type Language = "en" | "jp" | "cn";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Header
    "nav.perpetual": "Perpetual",
    "nav.1001x": "1001x",
    "nav.spot": "Spot",
    "nav.portfolio": "Portfolio",
    "nav.referral": "Referral",
    "nav.rewards": "Rewards",
    "nav.earn": "Earn",
    "nav.stake": "Stake",
    "nav.features": "Features",
    "nav.stats": "Stats",
    "nav.roadmap": "Roadmap",
    "more": "More",
    "button.launchApp": "Launch App",
    "button.connectWallet": "Connect wallet",
    
    // Home
    "home.nextGen": "NEXT-GENERATION PERPETUAL DEX",
    "home.heroTitle": "Trade Perpetuals with Maximum Capital Efficiency",
    "home.heroSubtitle": "Experience up to 100x leverage on crypto perpetuals with deep liquidity, minimal slippage, and institutional-grade execution. Built for traders who demand performance.",
    "home.unlock": "UNLOCK YOUR TRADING EDGE",
    "home.title": "Liquidity for all",
    "home.subtitle": "Ultra-fast decentralized perpetual exchange with deep liquidity, powered by advanced AI trading assistance.",
    "home.startTrading": "Start Trading",
    "home.learnMore": "Learn More",
    "home.24hVolume": "24h Volume",
    "home.cumulativeVolume": "Cumulative Volume",
    "home.addresses": "Addresses",
    "home.selfCustody": "Self-Custody",
    "home.lightningFast": "Lightning Fast Execution",
    "home.highPerformance": "High-Performance Trading for Everyone",
    "home.highPerformanceDesc": "Powerful trading engine designed for deep liquidity, speed, and security",
    "home.ultraDeepLiquidity": "Ultra-Deep Liquidity",
    "home.ultraDeepLiquidityDesc": "$10M+ depth within 1bps spreads, even during high volatility.",
    "home.highPerformanceTitle": "High Performance",
    "home.highPerformanceDesc2": "200,000+ orders per second, less than 10ms latency.",
    "home.provenSecurity": "Proven Security",
    "home.provenSecurityDesc": "Secured by Ethereum mainnet. Your Keys. Your Assets.",
    "home.leverage": "Up to 100x Leverage",
    "home.leverageDesc": "Trade with confidence using flexible leverage options on major pairs.",
    "home.earnYield": "Earn Yield",
    "home.earnYieldDesc": "Your collateral works for you. Earn passive yield automatically.",
    "home.multiChain": "Multi-Chain Support",
    "home.multiChainDesc": "One app, unlimited DeFi experience. Multi-chain, multi-protocol.",
    "home.readyToStart": "Ready to Start Trading?",
    "home.readyToStartDesc": "Join thousands of traders experiencing the future of perpetual trading.",
    "home.viewDocs": "View Documentation",
    "home.roadmapTitle": "Roadmap",
    "home.roadmapDesc": "Our journey to revolutionize decentralized perpetual trading",
    "roadmap.q1.title": "Q1 2026 - Foundation",
    "roadmap.q1.item1": "Development Kickoff",
    "roadmap.q1.item2": "Core Infrastructure Setup",
    "roadmap.q1.item3": "Smart Contract Security Audit",
    "roadmap.q1.item4": "Testnet Launch",
    "roadmap.q2.title": "Q2 2026 - Platform Launch",
    "roadmap.q2.item1": "Mainnet Launch",
    "roadmap.q2.item2": "First Airdrop Round",
    "roadmap.q2.item3": "Community Building",
    "roadmap.q2.item4": "Marketing Campaign",
    "roadmap.q3.title": "Q3 2026 - Expansion",
    "roadmap.q3.item1": "Second Airdrop Round",
    "roadmap.q3.item2": "Advanced Trading Features",
    "roadmap.q3.item3": "Multi-chain Support",
    "roadmap.q3.item4": "Mobile App Beta",
    "roadmap.q4.title": "Q4 2026 - Innovation",
    "roadmap.q4.item1": "NFT Trading Achievements",
    "roadmap.q4.item2": "VISA Card Integration",
    "roadmap.q4.item3": "Global Expansion",
    "roadmap.q4.item4": "Governance Launch",
    
    // Trade Page
    "trade.perpetual": "Perpetual",
    "trade.spot": "Spot",
    "trade.mark": "Mark",
    "trade.index": "Index",
    "trade.cross": "Cross",
    "trade.isolated": "Isolated",
    "trade.market": "Market",
    "trade.limit": "Limit",
    "trade.stopLimit": "Stop Limit",
    "trade.price": "Price (USDT)",
    "trade.size": "Size",
    "trade.margin": "Margin",
    "trade.max": "Max",
    "trade.buyLong": "Buy/Long",
    "trade.sellShort": "Sell/Short",
    "trade.buy": "Buy",
    "trade.sell": "Sell",
    "trade.positions": "Positions",
    "trade.openOrders": "Open Orders",
    "trade.orderHistory": "Order History",
    "trade.tradeHistory": "Trade History",
    "trade.noData": "No {type} yet",
    "trade.mid": "Mid",
    "trade.stop": "Stop",
    "trade.long": "Long",
    "trade.short": "Short",
    "trade.trades": "Trades",
    "trade.noPositions": "No positions yet",
    "trade.noOrders": "No open orders",
    "trade.noTrades": "No trades yet",
    "trade.close": "Close",
    "trade.cancel": "Cancel",
    "trade.amount": "Amount",
    "trade.available": "Available",
    "trade.limitPrice": "Limit Price",
    "trade.stopPrice": "Stop Price",
    
    // Referral
    "referral.title": "Invite friends, Earn together",
    "referral.subtitle": "Invite friends to trade on PerpX and earn commission on their trading fees.",
    "referral.learnMore": "Learn more about our referral program",
    "referral.inviteNow": "Invite now",
    "referral.youReceive": "You receive",
    "referral.inviteeReceive": "Your invitee receive",
    "referral.code": "Referral code",
    "referral.link": "Referral link",
    "referral.summary": "Summary",
    "referral.totalVolume": "Total Volume",
    "referral.rewards": "Referral rewards",
    "referral.friends": "Referred friends",
    "referral.tiers": "Referral tiers",
    "referral.list": "Referral list",
    "referral.tier": "Tier",
    "referral.commission": "Commission",
    "referral.tradingVolume": "Trading Volume",
    "referral.noReferrals": "No referrals yet",
    
    // Dashboard
    "dashboard.stage": "Stage",
    "dashboard.dawn": "Dawn",
    "dashboard.subtitle": "Track your trading performance and rewards",
    "dashboard.totalVolume": "Total Volume",
    "dashboard.pnl": "Total PnL",
    "dashboard.points": "Points Earned",
    "dashboard.rank": "Global Rank",
    
    // Stats
    "stats.title": "Platform Statistics",
    "stats.subtitle": "Real-time trading metrics and platform performance",
    "stats.volume24h": "24h Trading Volume",
    "stats.totalVolume": "Total Volume",
    "stats.totalTrades": "Total Trades",
    "stats.activeTraders": "Active Traders",
    "stats.topPairs": "Top Trading Pairs",
    "stats.recentTrades": "Recent Trades",
    "stats.openInterest": "Open Interest",
    "stats.totalUsers": "Total Users",
    "stats.topMarkets": "Top Markets (24h)",
    "stats.pair": "Pair",
    "stats.price": "Price",
    "stats.change": "Change",
    "stats.time": "Time",
    "stats.side": "Side",
    "stats.size": "Size",
    "stats.long": "Long",
    "stats.short": "Short",
    "stats.tradingVolume7d": "Trading Volume (7 Days)",
    "stats.userGrowth": "User Growth",
    "stats.newUsers24h": "New Users (24h)",
    "stats.activeUsers24h": "Active Users (24h)",
    "stats.totalTraders": "Total Traders",
    
    // Feedback
    "feedback.title": "Feedback",
    "feedback.subtitle": "Share your ideas and suggestions to help us improve",
    "feedback.category": "Category",
    "feedback.featureRequest": "Feature Request",
    "feedback.bugReport": "Bug Report",
    "feedback.generalFeedback": "General Feedback",
    "feedback.other": "Other",
    "feedback.titleLabel": "Title",
    "feedback.titlePlaceholder": "Brief summary of your feedback",
    "feedback.description": "Description",
    "feedback.descriptionPlaceholder": "Provide detailed information about your feedback...",
    "feedback.submit": "Submit Feedback",
    "feedback.recentCommunity": "Recent Community Feedback",
    "feedback.votes": "votes",
    "feedback.inProgress": "In Progress",
    "feedback.planned": "Planned",
    "feedback.underReview": "Under Review",
    
    // VIP
    "vip.title": "VIP Program",
    "vip.subtitle": "Unlock exclusive benefits and lower fees",
    "vip.currentTier": "Current Tier",
    "vip.benefits": "Benefits",
    "vip.requirements": "Requirements",
    "vip.tradingFee": "Trading Fee",
    "vip.withdrawalFee": "Withdrawal Fee",
    "vip.prioritySupport": "Priority Support",
    "vip.volumeRequired": "30-Day Volume Required",
    "vip.silver": "Silver",
    "vip.gold": "Gold",
    "vip.platinum": "Platinum",
    "vip.prioritySupportBenefit": "Priority support",
    "vip.reducedFees": "Reduced fees",
    "vip.earlyAccess": "Early access",
    "vip.allSilverBenefits": "All Silver benefits",
    "vip.dedicatedAccountManager": "Dedicated account manager",
    "vip.customApiLimits": "Custom API limits",
    "vip.allGoldBenefits": "All Gold benefits",
    "vip.zeroMakerFees": "Zero maker fees",
    "vip.exclusiveEvents": "Exclusive events",
    "vip.standard": "Standard",
    "vip.unlockMessage": "Trade $100K in the next 30 days to unlock Silver tier",
    "vip.allBenefits": "All Benefits",
    "vip.silverBadge": "Silver badge",
    "vip.goldBadge": "Gold badge",
    "vip.platinumBadge": "Platinum badge",
    "vip.monthlyReports": "Monthly trading reports",
    "vip.tradingInsights": "Advanced trading insights",
    "vip.priorityWithdrawals": "Priority withdrawals",
    "vip.advancedAnalytics": "Advanced analytics tools",
    "vip.customTradingTools": "Custom trading tools",
    "vip.personalizedSupport": "Personalized 24/7 support",
    "vip.earlyProductAccess": "Early access to new products",
    "vip.customLiquidity": "Custom liquidity solutions",
    "vip.directTeamAccess": "Direct access to development team",
    "vip.upgradeMessage": "Increase your trading volume to unlock VIP tiers and enjoy exclusive benefits.",
    
    // API
    "api.title": "API Documentation",
    "api.subtitle": "Build powerful trading applications with our API",
    "api.getStarted": "Get Started",
    "api.restApi": "REST API",
    "api.restApiDesc": "Access market data, place orders, and manage your account programmatically",
    "api.websocketApi": "WebSocket API",
    "api.websocketApiDesc": "Real-time market data and order updates via WebSocket connection",
    "api.viewDocumentation": "View Documentation",
    "api.keyManagement": "API Key Management",
    "api.productionKey": "Production API Key",
    "api.createdOn": "Created on",
    "api.revoke": "Revoke",
    "api.generateKey": "Generate New API Key",
    "api.quickStart": "Quick Start",
    "api.fullDocumentation": "Full Documentation",
    "api.viewExamples": "View Examples",
    "api.endpoints": "API Endpoints",
    "api.authentication": "Authentication",
    "api.rateLimit": "Rate Limiting",
    
    // Docs
    "docs.title": "Documentation",
    "docs.subtitle": "Learn how to use PerpX",
    "docs.gettingStarted": "Getting Started",
    "docs.gettingStartedDesc": "Learn the basics of PerpX",
    "docs.tradingGuide": "Trading Guide",
    "docs.tradingGuideDesc": "Master perpetual trading",
    "docs.apiReference": "API Reference",
    "docs.apiReferenceDesc": "Integrate with PerpX API",
    "docs.security": "Security",
    "docs.securityDesc": "Best practices for account security",
    "docs.faq": "FAQ",
    "docs.faqDesc": "Frequently asked questions",
    "docs.support": "Support",
    "docs.supportDesc": "Get help from our team",
    "docs.popularArticles": "Popular Articles",
    "docs.firstTrade": "How to place your first trade",
    "docs.leverage": "Understanding leverage and margin",
    "docs.apiKeys": "Setting up API keys",
    "docs.twoFactor": "Two-factor authentication setup",
    
    // Blog
    "blog.title": "Blog",
    "blog.subtitle": "Latest news and updates from PerpX",
    
    // Footer
    "footer.copyright": "© 2025 PerpX. All rights reserved.",
    "footer.privacyPolicy": "Privacy Policy",
    "footer.termsOfService": "Terms of Service",
    "blog.readMore": "Read More",
    "blog.comingSoon": "Coming Soon",
    
    // More Menu
    "more.feedback": "Feedback",
    "more.feedbackDesc": "Share your ideas and suggestions",
    "more.vip": "VIP",
    "more.vipDesc": "Enjoy lower trading fees",
    "more.api": "API",
    "more.apiDesc": "Apply for access to the API",
    "more.documentation": "Documentation",
    "more.documentationDesc": "Explore product features",
    "more.blog": "Blog",
    "more.blogDesc": "Stay updated with the latest news",
    "more.discord": "Discord",
    "more.discordDesc": "Join the Discord community",
    
    // Rewards
    "rewards.dailyTasks": "Daily Tasks",
    "rewards.weeklyTasks": "Weekly Tasks",
    "rewards.specialTasks": "Special Tasks",
    "rewards.loginBonus": "Login Bonus",
    "rewards.loginBonusDesc": "Get rewards by logging in daily",
    "rewards.demoTrade": "Complete 3 Demo Trades",
    "rewards.demoTradeDesc": "Experience trading in learning mode 3 times",
    "rewards.twitterPost": "Post on X (Twitter)",
    "rewards.twitterPostDesc": "Tweet about PerpX",
    "rewards.weeklyLogin": "7-Day Login Streak",
    "rewards.weeklyLoginDesc": "Log in daily for a week to get special rewards",
    "rewards.joinDiscord": "Join Discord",
    "rewards.joinDiscordDesc": "Join our official Discord server",
    "rewards.joinTelegram": "Join Telegram",
    "rewards.joinTelegramDesc": "Join our official Telegram group",
    "rewards.joinGuild": "Join a Guild",
    "rewards.joinGuildDesc": "Join a guild to get exclusive benefits",
    "rewards.login": "Login",
    "rewards.trade": "Trade",
    "rewards.post": "Post",
    "rewards.claim": "Claim Reward",
    "rewards.join": "Join",
    "rewards.points": "points",
    "rewards.completed": "Completed",
    "rewards.loginSuccess": "Login completed! Earned 1 point.",
    "rewards.demoSuccess": "Demo trade completed! Earned 5 points.",
    "rewards.snsSuccess": "SNS post completed! Earned 5 points.",
    "rewards.weeklyLoginSuccess": "7-day login streak achieved! Earned 10 points.",
    "rewards.communitySuccess": "Community joined! Earned 30 points.",
    "rewards.guildSuccess": "Guild joined! Earned 50 points (one-time only).",
    
    // Earn
    "earn.title": "Earn",
    "earn.subtitle": "Maximize your crypto earnings through liquidity provision and lending. Earn competitive yields while supporting the PerpDEX ecosystem.",
    "earn.totalValueLocked": "Total Value Locked",
    "earn.totalProviders": "Total Providers",
    "earn.averageApy": "Average APY",
    "earn.thisWeek": "this week",
    "earn.acrossAllPools": "across all pools",
    "earn.liquidityPools": "Liquidity Pools",
    "earn.pair": "Pair",
    "earn.apy": "APY",
    "earn.tvl": "TVL",
    "earn.volume24h": "24h Volume",
    "earn.rewards": "Rewards",
    "earn.action": "Action",
    "earn.addLiquidity": "Add Liquidity",
    "earn.lending": "Lending",
    "earn.asset": "Asset",
    "earn.supplyApy": "Supply APY",
    "earn.totalSupplied": "Total Supplied",
    "earn.available": "Available",
    "earn.utilization": "Utilization",
    "earn.supply": "Supply",
    "earn.benefits": "Benefits",
    "earn.secureProtocol": "Secure Protocol",
    "earn.secureProtocolDesc": "Audited smart contracts with multi-signature security and insurance coverage",
    "earn.autoCompounding": "Auto-Compounding",
    "earn.autoCompoundingDesc": "Rewards are automatically reinvested to maximize your returns over time",
    "earn.flexibleWithdrawal": "Flexible Withdrawal",
    "earn.flexibleWithdrawalDesc": "Withdraw your funds anytime with no lock-up periods or penalties",
    
    // Stake
    "stake.title": "Stake Assets",
    "stake.subtitle": "Earn passive income by staking your crypto assets. Choose from multiple assets with competitive APY rates and flexible lock periods.",
    "stake.totalValueLocked": "Total Value Locked",
    "stake.totalStakers": "Total Stakers",
    "stake.averageApy": "Average APY",
    "stake.thisWeek": "this week",
    "stake.acrossAllAssets": "across all assets",
    "stake.availableAssets": "Available Staking Assets",
    "stake.asset": "Asset",
    "stake.apy": "APY",
    "stake.tvl": "TVL",
    "stake.minStake": "Min Stake",
    "stake.lockPeriod": "Lock Period",
    "stake.action": "Action",
    "stake.stakeNow": "Stake Now",
    "stake.howItWorks": "How It Works",
    "stake.step1": "Select an asset you want to stake from the available options",
    "stake.step2": "Choose the amount you wish to stake (minimum stake required)",
    "stake.step3": "Confirm the lock period and APY rate",
    "stake.step4": "Start earning rewards automatically - withdraw after lock period ends",
    "stake.benefits": "Staking Benefits",
    "stake.benefit1": "Earn competitive APY rates on your idle crypto assets",
    "stake.benefit2": "Flexible lock periods from 7 to 30 days",
    "stake.benefit3": "Automatic reward distribution - no manual claiming needed",
    "stake.benefit4": "Secure staking powered by smart contracts on Ethereum mainnet",
    
    // Airdrop
    "airdrop.title": "PERPX Airdrop",
    "airdrop.subtitle": "Claim your PERPX tokens and become part of the PerpDEX community. Multiple rounds available for early adopters, traders, and contributors.",
    "airdrop.totalDistribution": "Total Distribution",
    "airdrop.eligibleUsers": "Eligible Users",
    "airdrop.claimed": "Already Claimed",
    "airdrop.checkEligibility": "Check Your Eligibility",
    "airdrop.connectWallet": "Connect your wallet to check eligibility",
    "airdrop.checkNow": "Check Eligibility",
    "airdrop.checking": "Checking...",
    "airdrop.eligible": "Congratulations! You're Eligible!",
    "airdrop.notEligible": "Not Eligible Yet",
    "airdrop.notEligibleDesc": "Keep trading and engaging with the community to qualify for future rounds",
    "airdrop.yourAllocation": "Your Allocation:",
    "airdrop.criteriaCheck": "Eligibility Criteria:",
    "airdrop.criteria.trading": "Completed at least 10 trades",
    "airdrop.criteria.volume": "Trading volume over $1,000",
    "airdrop.criteria.referral": "Referred at least 3 users",
    "airdrop.criteria.community": "Active community member",
    "airdrop.claimNow": "Claim Tokens",
    "airdrop.checkAgain": "Check Another Wallet",
    "airdrop.rounds": "Airdrop Rounds",
    "airdrop.active": "Active",
    "airdrop.upcoming": "Upcoming",
    "airdrop.ended": "Ended",
    "airdrop.totalAmount": "Total Amount",
    "airdrop.deadline": "Claim Deadline",
    "airdrop.howToQualify": "How to Qualify for Airdrops",
    "airdrop.tradingActivity": "Trading Activity",
    "airdrop.tradingActivityDesc": "Complete trades on PerpDEX to earn eligibility points",
    "airdrop.volumeRequirement": "Volume Requirement",
    "airdrop.volumeRequirementDesc": "Maintain consistent trading volume to qualify",
    "airdrop.referralProgram": "Referral Program",
    "airdrop.referralProgramDesc": "Invite friends and earn bonus allocation",
    "airdrop.communityEngagement": "Community Engagement",
    "airdrop.communityEngagementDesc": "Participate in governance and community activities",
  },
  jp: {
    // Header
    "nav.perpetual": "パーペチュアル",
    "nav.1001x": "1001x",
    "nav.spot": "スポット",
    "nav.portfolio": "ポートフォリオ",
    "nav.referral": "紹介",
    "nav.rewards": "報酬",
    "nav.earn": "獲得",
    "nav.stake": "ステーキング",
    "nav.features": "機能",
    "nav.stats": "統計",
    "nav.roadmap": "ロードマップ",
    "more": "その他",
    "button.launchApp": "アプリを起動",
    "button.connectWallet": "ウォレット接続",
    
    // Home
    "home.nextGen": "次世代型パーペチュアルDEX",
    "home.heroTitle": "最大の資本効率でパーペチュアル取引",
    "home.heroSubtitle": "最大100倍レバレッジ、深い流動性、最小限のスリッパージ、機関レベルの約定で暗号資産パーペチュアルを体験。パフォーマンスを求めるトレーダーのために構築。",
    "home.unlock": "取引の優位性を解放",
    "home.title": "すべての人に流動性を",
    "home.subtitle": "高度なAI取引支援を搭載した、深い流動性を持つ超高速分散型永続取引所。",
    "home.startTrading": "取引を開始",
    "home.learnMore": "詳細を見る",
    "home.24hVolume": "24時間取引高",
    "home.cumulativeVolume": "累計取引高",
    "home.addresses": "アドレス数",
    "home.selfCustody": "自己管理",
    "home.lightningFast": "超高速実行",
    "home.highPerformance": "すべての人のための高性能取引",
    "home.highPerformanceDesc": "深い流動性、スピード、セキュリティのために設計された強力な取引エンジン",
    "home.ultraDeepLiquidity": "超深い流動性",
    "home.ultraDeepLiquidityDesc": "高いボラティリティ時でも1bps以内で$10M+の深さ。",
    "home.highPerformanceTitle": "高性能",
    "home.highPerformanceDesc2": "毎秒200,000+注文、10ms未満のレイテンシ。",
    "home.provenSecurity": "実証済みのセキュリティ",
    "home.provenSecurityDesc": "Ethereumメインネットで保護。あなたの鍵。あなたの資産。",
    "home.leverage": "最大100倍レバレッジ",
    "home.leverageDesc": "主要ペアで柔軟なレバレッジオプションを使用して自信を持って取引。",
    "home.earnYield": "利回りを獲得",
    "home.earnYieldDesc": "あなたの担保があなたのために働きます。自動的に受動的利回りを獲得。",
    "home.multiChain": "マルチチェーン対応",
    "home.multiChainDesc": "1つのアプリ、無限のDeFi体験。マルチチェーン、マルチプロトコル。",
    "home.readyToStart": "取引を始める準備はできましたか?",
    "home.readyToStartDesc": "何千人ものトレーダーが永続取引の未来を体験しています。",
    "home.viewDocs": "ドキュメントを見る",
    "home.roadmapTitle": "ロードマップ",
    "home.roadmapDesc": "分散型永続取引に革命を起こす私たちの旅",
    "roadmap.q1.title": "2026年Q1 - 基盤構築",
    "roadmap.q1.item1": "開発キックオフ",
    "roadmap.q1.item2": "コアインフラ構築",
    "roadmap.q1.item3": "スマートコントラクトセキュリティ監査",
    "roadmap.q1.item4": "テストネットローンチ",
    "roadmap.q2.title": "2026年Q2 - プラットフォームローンチ",
    "roadmap.q2.item1": "メインネットローンチ",
    "roadmap.q2.item2": "第1回エアドロップ",
    "roadmap.q2.item3": "コミュニティ構築",
    "roadmap.q2.item4": "マーケティングキャンペーン",
    "roadmap.q3.title": "2026年Q3 - 拡大",
    "roadmap.q3.item1": "第2回エアドロップ",
    "roadmap.q3.item2": "高度な取引機能",
    "roadmap.q3.item3": "マルチチェーン対応",
    "roadmap.q3.item4": "モバイルアプリベータ版",
    "roadmap.q4.title": "2026年Q4 - イノベーション",
    "roadmap.q4.item1": "NFT取引実績",
    "roadmap.q4.item2": "VISAカード統合",
    "roadmap.q4.item3": "グローバル展開",
    "roadmap.q4.item4": "ガバナンスローンチ",
    
    // Trade Page
    "trade.perpetual": "パーペチュアル",
    "trade.spot": "スポット",
    "trade.mark": "マーク",
    "trade.index": "インデックス",
    "trade.cross": "クロス",
    "trade.isolated": "分離",
    "trade.market": "成行",
    "trade.limit": "指値",
    "trade.stopLimit": "ストップ指値",
    "trade.price": "価格 (USDT)",
    "trade.size": "数量",
    "trade.margin": "証拠金",
    "trade.max": "最大",
    "trade.buyLong": "買い/ロング",
    "trade.sellShort": "売り/ショート",
    "trade.buy": "買い",
    "trade.sell": "売り",
    "trade.positions": "ポジション",
    "trade.openOrders": "未約定注文",
    "trade.orderHistory": "注文履歴",
    "trade.tradeHistory": "取引履歴",
    "trade.noData": "{type}はまだありません",
    "trade.mid": "中値",
    "trade.stop": "ストップ",
    "trade.long": "ロング",
    "trade.short": "ショート",
    "trade.trades": "取引",
    "trade.noPositions": "ポジションはまだありません",
    "trade.noOrders": "未約定注文はありません",
    "trade.noTrades": "取引はまだありません",
    "trade.close": "決済",
    "trade.cancel": "キャンセル",
    "trade.amount": "数量",
    "trade.available": "利用可能",
    "trade.limitPrice": "指値価格",
    "trade.stopPrice": "ストップ価格",
    
    // Referral
    "referral.title": "友達を招待して、一緒に稼ごう",
    "referral.subtitle": "友達をPerpXに招待して、取引手数料のコミッションを獲得しましょう。",
    "referral.learnMore": "紹介プログラムの詳細を見る",
    "referral.inviteNow": "今すぐ招待",
    "referral.youReceive": "あなたが受け取る",
    "referral.inviteeReceive": "招待された人が受け取る",
    "referral.code": "紹介コード",
    "referral.link": "紹介リンク",
    "referral.summary": "概要",
    "referral.totalVolume": "合計取引高",
    "referral.rewards": "紹介報酬",
    "referral.friends": "紹介した友達",
    "referral.tiers": "紹介ティア",
    "referral.list": "紹介リスト",
    "referral.tier": "ティア",
    "referral.commission": "コミッション",
    "referral.tradingVolume": "取引高",
    "referral.noReferrals": "まだ紹介がありません",
    
    // Dashboard
    "dashboard.stage": "ステージ",
    "dashboard.dawn": "夜明け",
    "dashboard.subtitle": "取引パフォーマンスと報酬を追跡",
    "dashboard.totalVolume": "合計取引高",
    "dashboard.pnl": "合計損益",
    "dashboard.points": "獲得ポイント",
    "dashboard.rank": "グローバルランク",
    
    // Stats
    "stats.title": "プラットフォーム統計",
    "stats.subtitle": "リアルタイム取引メトリクスとプラットフォームパフォーマンス",
    "stats.volume24h": "24時間取引高",
    "stats.totalVolume": "合計取引高",
    "stats.totalTrades": "合計取引数",
    "stats.activeTraders": "アクティブトレーダー",
    "stats.topPairs": "トップ取引ペア",
    "stats.recentTrades": "最近の取引",
    "stats.openInterest": "未決済建玉",
    "stats.totalUsers": "総ユーザー数",
    "stats.topMarkets": "トップマーケット (24時間)",
    "stats.pair": "ペア",
    "stats.price": "価格",
    "stats.change": "変動",
    "stats.time": "時刻",
    "stats.side": "方向",
    "stats.size": "サイズ",
    "stats.long": "ロング",
    "stats.short": "ショート",
    "stats.tradingVolume7d": "取引高 (7日間)",
    "stats.userGrowth": "ユーザー成長",
    "stats.newUsers24h": "新規ユーザー (24時間)",
    "stats.activeUsers24h": "アクティブユーザー (24時間)",
    "stats.totalTraders": "総トレーダー数",
    
    // Feedback
    "feedback.title": "フィードバック",
    "feedback.subtitle": "改善のためのアイデアや提案を共有してください",
    "feedback.category": "カテゴリー",
    "feedback.featureRequest": "機能リクエスト",
    "feedback.bugReport": "バグ報告",
    "feedback.generalFeedback": "一般的なフィードバック",
    "feedback.other": "その他",
    "feedback.titleLabel": "タイトル",
    "feedback.titlePlaceholder": "フィードバックの概要",
    "feedback.description": "説明",
    "feedback.descriptionPlaceholder": "フィードバックの詳細情報を入力してください...",
    "feedback.submit": "フィードバックを送信",
    "feedback.recentCommunity": "最近のコミュニティフィードバック",
    "feedback.votes": "票",
    "feedback.inProgress": "進行中",
    "feedback.planned": "計画中",
    "feedback.underReview": "レビュー中",
    
    // VIP
    "vip.title": "VIPプログラム",
    "vip.subtitle": "限定特典と低手数料をアンロック",
    "vip.currentTier": "現在のティア",
    "vip.benefits": "特典",
    "vip.requirements": "要件",
    "vip.tradingFee": "取引手数料",
    "vip.withdrawalFee": "出金手数料",
    "vip.prioritySupport": "優先サポート",
    "vip.volumeRequired": "30日間の必要取引高",
    "vip.silver": "シルバー",
    "vip.gold": "ゴールド",
    "vip.platinum": "プラチナ",
    "vip.prioritySupportBenefit": "優先サポート",
    "vip.reducedFees": "手数料割引",
    "vip.earlyAccess": "早期アクセス",
    "vip.allSilverBenefits": "シルバーの全特典",
    "vip.dedicatedAccountManager": "専任アカウントマネージャー",
    "vip.customApiLimits": "カスタムAPI制限",
    "vip.allGoldBenefits": "ゴールドの全特典",
    "vip.zeroMakerFees": "メイカー手数料無料",
    "vip.exclusiveEvents": "限定イベント",
    "vip.standard": "スタンダード",
    "vip.unlockMessage": "30日間で10万ドル取引でシルバーティアをアンロック",
    "vip.allBenefits": "全ての特典",
    "vip.silverBadge": "シルバーバッジ",
    "vip.goldBadge": "ゴールドバッジ",
    "vip.platinumBadge": "プラチナバッジ",
    "vip.monthlyReports": "月次レポート",
    "vip.tradingInsights": "取引インサイト",
    "vip.priorityWithdrawals": "優先出金",
    "vip.advancedAnalytics": "高度な分析ツール",
    "vip.customTradingTools": "カスタム取引ツール",
    "vip.personalizedSupport": "パーソナライズドサポート",
    "vip.earlyProductAccess": "新製品への早期アクセス",
    "vip.customLiquidity": "カスタム流動性ソリューション",
    "vip.directTeamAccess": "開発チームへの直接アクセス",
    "vip.upgradeMessage": "取引量を増やしてVIPティアをアンロックし、限定特典をお楽しみください。",
    
    // API
    "api.title": "APIドキュメント",
    "api.subtitle": "APIで強力な取引アプリケーションを構築",
    "api.getStarted": "始める",
    "api.restApi": "REST API",
    "api.restApiDesc": "市場データへのアクセス、注文の発注、アカウント管理をプログラムで実行",
    "api.websocketApi": "WebSocket API",
    "api.websocketApiDesc": "WebSocket接続によるリアルタイム市場データと注文更新",
    "api.viewDocumentation": "ドキュメントを見る",
    "api.keyManagement": "APIキー管理",
    "api.productionKey": "本番APIキー",
    "api.createdOn": "作成日",
    "api.revoke": "取り消す",
    "api.generateKey": "新しいAPIキーを生成",
    "api.quickStart": "クイックスタート",
    "api.fullDocumentation": "完全なドキュメント",
    "api.viewExamples": "例を見る",
    "api.endpoints": "APIエンドポイント",
    "api.authentication": "認証",
    "api.rateLimit": "レート制限",
       // Docs
    "docs.title": "ドキュメント",
    "docs.subtitle": "PerpXの使い方を学ぶ",
    "docs.gettingStarted": "はじめに",
    "docs.gettingStartedDesc": "PerpXの基本を学ぶ",
    "docs.tradingGuide": "取引ガイド",
    "docs.tradingGuideDesc": "パーペチュアル取引をマスター",
    "docs.apiReference": "APIリファレンス",
    "docs.apiReferenceDesc": "PerpX APIと統合",
    "docs.security": "セキュリティ",
    "docs.securityDesc": "アカウントセキュリティのベストプラクティス",
    "docs.faq": "よくある質問",
    "docs.faqDesc": "よくある質問",
    "docs.support": "サポート",
    "docs.supportDesc": "チームからサポートを受ける",
    "docs.popularArticles": "人気記事",
    "docs.firstTrade": "初めての取引方法",
    "docs.leverage": "レバレッジと証拠金を理解する",
    "docs.apiKeys": "APIキーの設定",
    "docs.twoFactor": "二段階認証の設定",
    
    // Blog
    "blog.title": "ブログ",
    "blog.subtitle": "PerpXの最新ニュースとアップデート",
    
    // Footer
    "footer.copyright": "© 2025 PerpX. All rights reserved.",
    "footer.privacyPolicy": "プライバシーポリシー",
    "footer.termsOfService": "利用規約",
    "blog.readMore": "続きを読む",
    "blog.comingSoon": "近日公開",
    
    // More Menu
    "more.feedback": "フィードバック",
    "more.feedbackDesc": "アイデアや提案を共有",
    "more.vip": "VIP",
    "more.vipDesc": "低手数料を享受",
    "more.api": "API",
    "more.apiDesc": "APIアクセスを申請",
    "more.documentation": "ドキュメント",
    "more.documentationDesc": "製品機能を探索",
    "more.blog": "ブログ",
    "more.blogDesc": "最新ニュースをチェック",
    "more.discord": "Discord",
    "more.discordDesc": "Discordコミュニティに参加",
    
    // Rewards
    "rewards.dailyTasks": "デイリータスク",
    "rewards.weeklyTasks": "ウィークリータスク",
    "rewards.specialTasks": "特別タスク",
    "rewards.loginBonus": "ログインボーナス",
    "rewards.loginBonusDesc": "毎日ログインして報酬を獲得",
    "rewards.demoTrade": "デモ取引を3回実行",
    "rewards.demoTradeDesc": "学習モードで3回取引を体験",
    "rewards.twitterPost": "X (Twitter) に投稿",
    "rewards.twitterPostDesc": "PerpXについてツイート",
    "rewards.weeklyLogin": "7日連続ログイン",
    "rewards.weeklyLoginDesc": "1週間毎日ログインして特別報酬を獲得",
    "rewards.joinDiscord": "Discordに参加",
    "rewards.joinDiscordDesc": "公式Discordサーバーに参加",
    "rewards.joinTelegram": "Telegramに参加",
    "rewards.joinTelegramDesc": "公式Telegramグループに参加",
    "rewards.joinGuild": "ギルドに参加",
    "rewards.joinGuildDesc": "ギルドに参加して限定特典を獲得",
    "rewards.login": "ログイン",
    "rewards.trade": "取引する",
    "rewards.post": "投稿する",
    "rewards.claim": "報酬を受け取る",
    "rewards.join": "参加する",
    "rewards.points": "ポイント",
    "rewards.completed": "完了",
    "rewards.loginSuccess": "ログイン完了！1ポイント獲得しました。",
    "rewards.demoSuccess": "デモ取引完了！5ポイント獲得しました。",
    "rewards.snsSuccess": "SNS投稿完了！5ポイント獲得しました。",
    "rewards.weeklyLoginSuccess": "7日連続ログイン達成！10ポイント獲得しました。",
    "rewards.communitySuccess": "コミュニティ参加完了！30ポイント獲得しました。",
    "rewards.guildSuccess": "ギルド参加完了！50ポイント獲得しました（一回限り）。",
    
    // Earn
    "earn.title": "獲得",
    "earn.subtitle": "流動性提供とレンディングを通じて暗号資産の収益を最大化。PerpDEXエコシステムをサポートしながら競争力のある利回りを獲得。",
    "earn.totalValueLocked": "総ロック額",
    "earn.totalProviders": "総プロバイダー数",
    "earn.averageApy": "平均APY",
    "earn.thisWeek": "今週",
    "earn.acrossAllPools": "全プール平均",
    "earn.liquidityPools": "流動性プール",
    "earn.pair": "ペア",
    "earn.apy": "APY",
    "earn.tvl": "TVL",
    "earn.volume24h": "24時間取引高",
    "earn.rewards": "報酬",
    "earn.action": "操作",
    "earn.addLiquidity": "流動性を追加",
    "earn.lending": "レンディング",
    "earn.asset": "資産",
    "earn.supplyApy": "供給APY",
    "earn.totalSupplied": "総供給量",
    "earn.available": "利用可能",
    "earn.utilization": "利用率",
    "earn.supply": "供給",
    "earn.benefits": "メリット",
    "earn.secureProtocol": "安全なプロトコル",
    "earn.secureProtocolDesc": "監査済みスマートコントラクト、マルチシグセキュリティ、保険適用",
    "earn.autoCompounding": "自動複利",
    "earn.autoCompoundingDesc": "報酬は自動的に再投資され、時間とともにリターンを最大化",
    "earn.flexibleWithdrawal": "柔軟な引き出し",
    "earn.flexibleWithdrawalDesc": "ロックアップ期間やペナルティなしでいつでも資金を引き出し可能",
    
    // Stake
    "stake.title": "ステーキング",
    "stake.subtitle": "暗号資産をステーキングして受動的収入を獲得。競争力のあるAPYレートと柔軟なロック期間から複数の資産を選択できます。",
    "stake.totalValueLocked": "総ロック額",
    "stake.totalStakers": "総ステーカー数",
    "stake.averageApy": "平均APY",
    "stake.thisWeek": "今週",
    "stake.acrossAllAssets": "全資産平均",
    "stake.availableAssets": "利用可能なステーキング資産",
    "stake.asset": "資産",
    "stake.apy": "APY",
    "stake.tvl": "TVL",
    "stake.minStake": "最小ステーク額",
    "stake.lockPeriod": "ロック期間",
    "stake.action": "操作",
    "stake.stakeNow": "今すぐステーク",
    "stake.howItWorks": "仕組み",
    "stake.step1": "利用可能なオプションからステーキングしたい資産を選択",
    "stake.step2": "ステーキングする金額を選択（最小ステーク額が必要）",
    "stake.step3": "ロック期間とAPYレートを確認",
    "stake.step4": "自動的に報酬を獲得開始 - ロック期間終了後に引き出し可能",
    "stake.benefits": "ステーキングのメリット",
    "stake.benefit1": "遊休暗号資産で競争力のあるAPYレートを獲得",
    "stake.benefit2": "7日から30日までの柔軟なロック期間",
    "stake.benefit3": "自動報酬配布 - 手動請求不要",
    "stake.benefit4": "Ethereumメインネット上のスマートコントラクトによる安全なステーキング",
    
    // Airdrop
    "airdrop.title": "PERPXエアドロップ",
    "airdrop.subtitle": "PERPXトークンを請求してPerpDEXコミュニティの一員になりましょう。アーリーアダプター、トレーダー、貢献者向けに複数のラウンドを用意。",
    "airdrop.totalDistribution": "総配布量",
    "airdrop.eligibleUsers": "対象ユーザー数",
    "airdrop.claimed": "請求済み",
    "airdrop.checkEligibility": "対象資格を確認",
    "airdrop.connectWallet": "ウォレットを接続して対象資格を確認",
    "airdrop.checkNow": "今すぐ確認",
    "airdrop.checking": "確認中...",
    "airdrop.eligible": "おめでとうございます！対象です！",
    "airdrop.notEligible": "まだ対象ではありません",
    "airdrop.notEligibleDesc": "取引を続け、コミュニティに参加して将来のラウンドの資格を得ましょう",
    "airdrop.yourAllocation": "あなたの割り当て：",
    "airdrop.criteriaCheck": "対象基準：",
    "airdrop.criteria.trading": "少なくとも10回の取引を完了",
    "airdrop.criteria.volume": "取引量$1,000以上",
    "airdrop.criteria.referral": "少なくとも3人のユーザーを紹介",
    "airdrop.criteria.community": "アクティブなコミュニティメンバー",
    "airdrop.claimNow": "トークンを請求",
    "airdrop.checkAgain": "別のウォレットを確認",
    "airdrop.rounds": "エアドロップラウンド",
    "airdrop.active": "アクティブ",
    "airdrop.upcoming": "予定",
    "airdrop.ended": "終了",
    "airdrop.totalAmount": "総量",
    "airdrop.deadline": "請求期限",
    "airdrop.howToQualify": "エアドロップの資格を得る方法",
    "airdrop.tradingActivity": "取引活動",
    "airdrop.tradingActivityDesc": "PerpDEXで取引を完了して資格ポイントを獲得",
    "airdrop.volumeRequirement": "取引量要件",
    "airdrop.volumeRequirementDesc": "一貫した取引量を維持して資格を得る",
    "airdrop.referralProgram": "紹介プログラム",
    "airdrop.referralProgramDesc": "友達を招待してボーナス割り当てを獲得",
    "airdrop.communityEngagement": "コミュニティ参加",
    "airdrop.communityEngagementDesc": "ガバナンスやコミュニティ活動に参加",
  },
  cn: {
    // Header
    "nav.perpetual": "永续合约",
    "nav.1001x": "1001x",
    "nav.spot": "现货",
    "nav.portfolio": "投资组合",
    "nav.referral": "推荐",
    "nav.rewards": "奖励",
    "nav.earn": "赚取",
    "nav.stake": "质押",
    "nav.features": "功能",
    "nav.stats": "统计",
    "nav.roadmap": "路线图",
    "more": "更多",
    "button.launchApp": "启动应用",
    "button.connectWallet": "连接钱包",
    
    // Home
    "home.nextGen": "下一代永续合约DEX",
    "home.heroTitle": "以最大资本效率交易永续合约",
    "home.heroSubtitle": "体验高达100倍杠杆的加密货币永续合约交易，深度流动性、最小滑点和机构级执行。为追求性能的交易者打造。",
    "home.unlock": "释放您的交易优势",
    "home.title": "为所有人提供流动性",
    "home.subtitle": "超快速去中心化永续交易所，具有深度流动性，由先进的AI交易辅助提供支持。",
    "home.startTrading": "开始交易",
    "home.learnMore": "了解更多",
    "home.24hVolume": "24小时交易量",
    "home.cumulativeVolume": "累计交易量",
    "home.addresses": "地址数",
    "home.selfCustody": "自我托管",
    "home.lightningFast": "闪电般快速执行",
    "home.highPerformance": "为所有人提供高性能交易",
    "home.highPerformanceDesc": "为深度流动性、速度和安全性设计的强大交易引擎",
    "home.ultraDeepLiquidity": "超深流动性",
    "home.ultraDeepLiquidityDesc": "即使在高波动性期间，1bps价差内也有$10M+深度。",
    "home.highPerformanceTitle": "高性能",
    "home.highPerformanceDesc2": "每秒200,000+订单，延迟低于10ms。",
    "home.provenSecurity": "经过验证的安全性",
    "home.provenSecurityDesc": "由以太坊主网保护。您的密钥。您的资产。",
    "home.leverage": "高达100倍杠杆",
    "home.leverageDesc": "在主要交易对上使用灵活的杠杆选项自信交易。",
    "home.earnYield": "赚取收益",
    "home.earnYieldDesc": "您的抵押品为您工作。自动赚取被动收益。",
    "home.multiChain": "多链支持",
    "home.multiChainDesc": "一个应用，无限的DeFi体验。多链，多协议。",
    "home.readyToStart": "准备开始交易了吗？",
    "home.readyToStartDesc": "加入成千上万的交易者，体验永续交易的未来。",
    "home.viewDocs": "查看文档",
    "home.roadmapTitle": "路线图",
    "home.roadmapDesc": "我们革新去中心化永续交易的旅程",
    "roadmap.q1.title": "2026年Q1 - 基础建设",
    "roadmap.q1.item1": "开发启动",
    "roadmap.q1.item2": "核心基础设施搭建",
    "roadmap.q1.item3": "智能合约安全审计",
    "roadmap.q1.item4": "测试网启动",
    "roadmap.q2.title": "2026年Q2 - 平台启动",
    "roadmap.q2.item1": "主网启动",
    "roadmap.q2.item2": "第一轮空投",
    "roadmap.q2.item3": "社区建设",
    "roadmap.q2.item4": "营销活动",
    "roadmap.q3.title": "2026年Q3 - 扩展",
    "roadmap.q3.item1": "第二轮空投",
    "roadmap.q3.item2": "高级交易功能",
    "roadmap.q3.item3": "多链支持",
    "roadmap.q3.item4": "移动应用测试版",
    "roadmap.q4.title": "2026年Q4 - 创新",
    "roadmap.q4.item1": "NFT交易成就",
    "roadmap.q4.item2": "VISA卡集成",
    "roadmap.q4.item3": "全球扩张",
    "roadmap.q4.item4": "治理启动",
    
    // Trade Page
    "trade.perpetual": "永续合约",
    "trade.spot": "现货",
    "trade.mark": "标记",
    "trade.index": "指数",
    "trade.cross": "全仓",
    "trade.isolated": "逐仓",
    "trade.market": "市价",
    "trade.limit": "限价",
    "trade.stopLimit": "止损限价",
    "trade.price": "价格 (USDT)",
    "trade.size": "数量",
    "trade.margin": "保证金",
    "trade.max": "最大",
    "trade.buyLong": "买入/做多",
    "trade.sellShort": "卖出/做空",
    "trade.buy": "买入",
    "trade.sell": "卖出",
    "trade.positions": "持仓",
    "trade.openOrders": "当前委托",
    "trade.orderHistory": "历史订单",
    "trade.tradeHistory": "成交历史",
    "trade.noData": "暂无{type}",
    "trade.mid": "中间价",
    "trade.stop": "止损",
    "trade.long": "做多",
    "trade.short": "做空",
    "trade.trades": "成交",
    "trade.noPositions": "暂无持仓",
    "trade.noOrders": "暂无当前委托",
    "trade.noTrades": "暂无成交",
    "trade.close": "平仓",
    "trade.cancel": "取消",
    "trade.amount": "数量",
    "trade.available": "可用",
    "trade.limitPrice": "限价",
    "trade.stopPrice": "止损价格",
    
    // Referral
    "referral.title": "邀请好友，共同赚取",
    "referral.subtitle": "邀请好友在PerpX上交易，赚取他们交易手续费的佣金。",
    "referral.learnMore": "了解更多关于我们的推荐计划",
    "referral.inviteNow": "立即邀请",
    "referral.youReceive": "您将获得",
    "referral.inviteeReceive": "您的被邀请人将获得",
    "referral.code": "推荐码",
    "referral.link": "推荐链接",
    "referral.summary": "概要",
    "referral.totalVolume": "总交易量",
    "referral.rewards": "推荐奖励",
    "referral.friends": "推荐好友",
    "referral.tiers": "推荐等级",
    "referral.list": "推荐列表",
    "referral.tier": "等级",
    "referral.commission": "佣金",
    "referral.tradingVolume": "交易量",
    "referral.noReferrals": "暂无推荐",
    
    // Dashboard
    "dashboard.stage": "阶段",
    "dashboard.dawn": "黎明",
    "dashboard.subtitle": "追踪您的交易表现和奖励",
    "dashboard.totalVolume": "总交易量",
    "dashboard.pnl": "总盈亏",
    "dashboard.points": "获得积分",
    "dashboard.rank": "全球排名",
    
    // Stats
    "stats.title": "平台统计",
    "stats.subtitle": "实时交易指标和平台性能",
    "stats.volume24h": "24小时交易量",
    "stats.totalVolume": "总交易量",
    "stats.totalTrades": "总交易数",
    "stats.activeTraders": "活跃交易者",
    "stats.topPairs": "热门交易对",
    "stats.recentTrades": "最近交易",
    "stats.openInterest": "未平仓合约",
    "stats.totalUsers": "总用户数",
    "stats.topMarkets": "热门市场 (24小时)",
    "stats.pair": "交易对",
    "stats.price": "价格",
    "stats.change": "涨跌",
    "stats.time": "时间",
    "stats.side": "方向",
    "stats.size": "数量",
    "stats.long": "做多",
    "stats.short": "做空",
    "stats.tradingVolume7d": "交易量 (7天)",
    "stats.userGrowth": "用户增长",
    "stats.newUsers24h": "新增用户 (24小时)",
    "stats.activeUsers24h": "活跃用户 (24小时)",
    "stats.totalTraders": "总交易者数",
    
    // Feedback
    "feedback.title": "反馈",
    "feedback.subtitle": "分享您的想法和建议帮助我们改进",
    "feedback.category": "类别",
    "feedback.featureRequest": "功能请求",
    "feedback.bugReport": "错误报告",
    "feedback.generalFeedback": "一般反馈",
    "feedback.other": "其他",
    "feedback.titleLabel": "标题",
    "feedback.titlePlaceholder": "反馈的简要摘要",
    "feedback.description": "描述",
    "feedback.descriptionPlaceholder": "提供关于您反馈的详细信息...",
    "feedback.submit": "提交反馈",
    "feedback.recentCommunity": "最近的社区反馈",
    "feedback.votes": "票",
    "feedback.inProgress": "进行中",
    "feedback.planned": "已计划",
    "feedback.underReview": "审核中",
    
    // VIP
    "vip.title": "VIP计划",
    "vip.subtitle": "解锁专属福利和更低费用",
    "vip.currentTier": "当前等级",
    "vip.benefits": "福利",
    "vip.requirements": "要求",
    "vip.tradingFee": "交易费",
    "vip.withdrawalFee": "提现费",
    "vip.prioritySupport": "优先支持",
    "vip.volumeRequired": "30天所需交易量",
    "vip.silver": "白银",
    "vip.gold": "黄金",
    "vip.platinum": "铂金",
    "vip.prioritySupportBenefit": "优先支持",
    "vip.reducedFees": "降低手续费",
    "vip.earlyAccess": "提前访问",
    "vip.allSilverBenefits": "所有白银优惠",
    "vip.dedicatedAccountManager": "专属客户经理",
    "vip.customApiLimits": "自定义API限制",
    "vip.allGoldBenefits": "所有黄金优惠",
    "vip.zeroMakerFees": "零Maker手续费",
    "vip.exclusiveEvents": "专属活动",
    "vip.standard": "标准",
    "vip.unlockMessage": "在30天内交易$100K解锁白银等级",
    "vip.allBenefits": "所有福利",
    "vip.silverBadge": "白银徽章",
    "vip.goldBadge": "黄金徽章",
    "vip.platinumBadge": "铂金徽章",
    "vip.monthlyReports": "月度交易报告",
    "vip.tradingInsights": "高级交易洞察",
    "vip.priorityWithdrawals": "优先提现",
    "vip.advancedAnalytics": "高级分析工具",
    "vip.customTradingTools": "自定义交易工具",
    "vip.personalizedSupport": "个性化24/7支持",
    "vip.earlyProductAccess": "新产品抢先体验",
    "vip.customLiquidity": "定制流动性解决方案",
    "vip.directTeamAccess": "直接联系开发团队",
    "vip.upgradeMessage": "增加您的交易量以解锁VIP等级，享受专属福利。",
    
    // API
    "api.title": "API文档",
    "api.subtitle": "使用我们的API构建强大的交易应用",
    "api.getStarted": "开始使用",
    "api.restApi": "REST API",
    "api.restApiDesc": "以编程方式访问市场数据、下单和管理账户",
    "api.websocketApi": "WebSocket API",
    "api.websocketApiDesc": "通过WebSocket连接获取实时市场数据和订单更新",
    "api.viewDocumentation": "查看文档",
    "api.keyManagement": "API密钥管理",
    "api.productionKey": "生产API密钥",
    "api.createdOn": "创建于",
    "api.revoke": "撤销",
    "api.generateKey": "生成新API密钥",
    "api.quickStart": "快速开始",
    "api.fullDocumentation": "完整文档",
    "api.viewExamples": "查看示例",
    "api.endpoints": "API端点",
    "api.authentication": "身份验证",
    "api.rateLimit": "速率限制",
     // Docs
    "docs.title": "文档",
    "docs.subtitle": "学习如何使用PerpX",
    "docs.gettingStarted": "入门指南",
    "docs.gettingStartedDesc": "学习PerpX基础",
    "docs.tradingGuide": "交易指南",
    "docs.tradingGuideDesc": "掌握永续合约交易",
    "docs.apiReference": "API参考",
    "docs.apiReferenceDesc": "与PerpX API集成",
    "docs.security": "安全",
    "docs.securityDesc": "账户安全最佳实践",
    "docs.faq": "常见问题",
    "docs.faqDesc": "常见问题解答",
    "docs.support": "支持",
    "docs.supportDesc": "从我们的团队获得帮助",
    "docs.popularArticles": "热门文章",
    "docs.firstTrade": "如何进行首次交易",
    "docs.leverage": "理解杠杆和保证金",
    "docs.apiKeys": "设置API密钥",
    "docs.twoFactor": "两步验证设置",
    
    // Blog
    "blog.title": "博客",
    "blog.subtitle": "PerpX的最新新闻和更新",
    
    // Footer
    "footer.copyright": "© 2025 PerpX. 保留所有权利。",
    "footer.privacyPolicy": "隐私政策",
    "footer.termsOfService": "服务条款",
    "blog.readMore": "阅读更多",
    "blog.comingSoon": "即将推出",
    
    // More Menu
    "more.feedback": "反馈",
    "more.feedbackDesc": "分享您的想法和建议",
    "more.vip": "VIP",
    "more.vipDesc": "享受更低交易费",
    "more.api": "API",
    "more.apiDesc": "申请API访问权限",
    "more.documentation": "文档",
    "more.documentationDesc": "探索产品功能",
    "more.blog": "博客",
    "more.blogDesc": "了解最新新闻",
    "more.discord": "Discord",
    "more.discordDesc": "加入Discord社区",
    
    // Rewards
    "rewards.dailyTasks": "每日任务",
    "rewards.weeklyTasks": "每周任务",
    "rewards.specialTasks": "特殊任务",
    "rewards.loginBonus": "登录奖励",
    "rewards.loginBonusDesc": "每天登录获得奖励",
    "rewards.demoTrade": "完成3次模拟交易",
    "rewards.demoTradeDesc": "在学习模式下体验3次交易",
    "rewards.twitterPost": "在X (Twitter)上发布",
    "rewards.twitterPostDesc": "发推文介绍PerpX",
    "rewards.weeklyLogin": "连续登录7天",
    "rewards.weeklyLoginDesc": "每天登录一周以获得特殊奖励",
    "rewards.joinDiscord": "加入Discord",
    "rewards.joinDiscordDesc": "加入我们的官方Discord服务器",
    "rewards.joinTelegram": "加入Telegram",
    "rewards.joinTelegramDesc": "加入我们的官方Telegram群组",
    "rewards.joinGuild": "加入公会",
    "rewards.joinGuildDesc": "加入公会获得独家福利",
    "rewards.login": "登录",
    "rewards.trade": "交易",
    "rewards.post": "发布",
    "rewards.claim": "领取奖励",
    "rewards.join": "加入",
    "rewards.points": "积分",
    "rewards.completed": "已完成",
    "rewards.loginSuccess": "登录完成！获得1积分。",
    "rewards.demoSuccess": "模拟交易完成！获得5积分。",
    "rewards.snsSuccess": "SNS发布完成！获得5积分。",
    "rewards.weeklyLoginSuccess": "连续登录7天达成！获得10积分。",
    "rewards.communitySuccess": "社区加入完成！获得30积分。",
    "rewards.guildSuccess": "公会加入完成！获得50积分（仅限一次）。",
    
    // Earn
    "earn.title": "赚取",
    "earn.subtitle": "通过流动性提供和借贷最大化加密资产收益。在支持PerpDEX生态系统的同时获得具有竞争力的收益率。",
    "earn.totalValueLocked": "总锁定价值",
    "earn.totalProviders": "总提供者数",
    "earn.averageApy": "平均APY",
    "earn.thisWeek": "本周",
    "earn.acrossAllPools": "所有池平均",
    "earn.liquidityPools": "流动性池",
    "earn.pair": "交易对",
    "earn.apy": "APY",
    "earn.tvl": "TVL",
    "earn.volume24h": "24小时交易量",
    "earn.rewards": "奖励",
    "earn.action": "操作",
    "earn.addLiquidity": "添加流动性",
    "earn.lending": "借贷",
    "earn.asset": "资产",
    "earn.supplyApy": "供应APY",
    "earn.totalSupplied": "总供应量",
    "earn.available": "可用",
    "earn.utilization": "利用率",
    "earn.supply": "供应",
    "earn.benefits": "优势",
    "earn.secureProtocol": "安全协议",
    "earn.secureProtocolDesc": "经过审计的智能合约，多签名安全和保险覆盖",
    "earn.autoCompounding": "自动复利",
    "earn.autoCompoundingDesc": "奖励自动再投资，随时间推移最大化您的回报",
    "earn.flexibleWithdrawal": "灵活提取",
    "earn.flexibleWithdrawalDesc": "无锁定期或罚款，随时提取资金",
    
    // Stake
    "stake.title": "质押资产",
    "stake.subtitle": "通过质押加密资产获得被动收入。从多种具有竞争力APY率和灵活锁定期的资产中选择。",
    "stake.totalValueLocked": "总锁定价值",
    "stake.totalStakers": "总质押者数",
    "stake.averageApy": "平均APY",
    "stake.thisWeek": "本周",
    "stake.acrossAllAssets": "所有资产平均",
    "stake.availableAssets": "可用质押资产",
    "stake.asset": "资产",
    "stake.apy": "APY",
    "stake.tvl": "TVL",
    "stake.minStake": "最小质押量",
    "stake.lockPeriod": "锁定期",
    "stake.action": "操作",
    "stake.stakeNow": "立即质押",
    "stake.howItWorks": "如何运作",
    "stake.step1": "从可用选项中选择您想质押的资产",
    "stake.step2": "选择您希望质押的数量（需要最小质押量）",
    "stake.step3": "确认锁定期和APY率",
    "stake.step4": "开始自动获得奖励 - 锁定期结束后可提取",
    "stake.benefits": "质押优势",
    "stake.benefit1": "在闲置的加密资产上赚取有竞争力的APY率",
    "stake.benefit2": "从7天到30天的灵活锁定期",
    "stake.benefit3": "自动奖励分配 - 无需手动领取",
    "stake.benefit4": "由以太坊主网上的智能合约提供支持的安全质押",
    
    // Airdrop
    "airdrop.title": "PERPX空投",
    "airdrop.subtitle": "领取您的PERPX代币，成为PerpDEX社区的一员。为早期采用者、交易者和贡献者提供多轮空投。",
    "airdrop.totalDistribution": "总分配量",
    "airdrop.eligibleUsers": "符合条件用户",
    "airdrop.claimed": "已领取",
    "airdrop.checkEligibility": "检查资格",
    "airdrop.connectWallet": "连接钱包以检查资格",
    "airdrop.checkNow": "立即检查",
    "airdrop.checking": "检查中...",
    "airdrop.eligible": "恭喜！您符合条件！",
    "airdrop.notEligible": "尚不符合条件",
    "airdrop.notEligibleDesc": "继续交易并参与社区活动，以符合未来轮次的资格",
    "airdrop.yourAllocation": "您的分配：",
    "airdrop.criteriaCheck": "资格标准：",
    "airdrop.criteria.trading": "完成至少10笔交易",
    "airdrop.criteria.volume": "交易量超过$1,000",
    "airdrop.criteria.referral": "推荐至少3位用户",
    "airdrop.criteria.community": "活跃社区成员",
    "airdrop.claimNow": "领取代币",
    "airdrop.checkAgain": "检查其他钱包",
    "airdrop.rounds": "空投轮次",
    "airdrop.active": "进行中",
    "airdrop.upcoming": "即将开始",
    "airdrop.ended": "已结束",
    "airdrop.totalAmount": "总量",
    "airdrop.deadline": "领取截止日期",
    "airdrop.howToQualify": "如何获得空投资格",
    "airdrop.tradingActivity": "交易活动",
    "airdrop.tradingActivityDesc": "在PerpDEX上完成交易以赚取资格积分",
    "airdrop.volumeRequirement": "交易量要求",
    "airdrop.volumeRequirementDesc": "保持稳定的交易量以符合资格",
    "airdrop.referralProgram": "推荐计划",
    "airdrop.referralProgramDesc": "邀请朋友并赚取额外分配",
    "airdrop.communityEngagement": "社区参与",
    "airdrop.communityEngagementDesc": "参与治理和社区活动",
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("en");

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.en] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}

